### ISSUE TITLE
Add ability to optionally include/exclude groundwater in SimplyC

### ISSUE THREAD

**Issue by LeahJB** [NIVANorge/Mobius#13]
Currently all groundwater-related processes and equations are commented out in SimplyC, and need uncommenting if you want groundwater. Instead, use the same approach as in SimplyQ, and add #define SIMPLYQ_GROUNDWATER to SimplyC.h and .cpp and reorganise contents of SimplyC.h

**Comment by Maginor** [comment]
dONE,
