### ISSUE TITLE
Add a reach branch visualiser to the Python wrapper

### ISSUE THREAD

**Issue by LeahJB** [NIVANorge/Mobius#9]
This has been done within MobiView, but could be useful to have for people working just within the Python wrapper.

For example:
https://nbviewer.jupyter.org/github/JamesSample/rid/blob/master/notebooks/simple_network_model.ipynb#NetworkX

The connectivity information is already exposed in mobius.py in the function list_of_inputs = dataset.get_branch_inputs("Reaches", "the reach you want the inputs of"). Just a matter of building a graph object from that that can be passed to the visualisation.

**Comment by JamesSample** [comment]
Closed by da768ba291b3d3fd47a121873af4b6cb4d55ee83 and 7dee568673eb567341baee7dc0d8a9565e7b3427.
